### PR TITLE
Facebook assignment

### PR DESCRIPTION
**Pull request by ansul90**

### CODE REVIEW

**Comment by mallelapavank** [comment]
Ansul you don't need to push all those files. Only activity_main.xml and its output screenshot should be uploaded. And of course your journal update. Please remove all the remaining files

**Comment by mallelapavank** [comment]
Also add help view (little ? at the right bottom)

**Comment by mallelapavank** [comment]
You still din't add the help view at the bottom right corner. Make changes later. I'm merging for now.

**Comment by vramana** [comment]
@mallelapavank Use Squash and merge option. It puts a single clean commit on the master.

**Comment by mallelapavank** [comment]
@vramana ok will do

**Pull request merged**
