### PR TITLE
Assignment 5

### PR DESCRIPTION
**Pull request by shivakrishna9**

### CODE REVIEW

**Comment by shivakrishna9** [comment]
I always create branch for every commit. Why is there a conflict?

**Comment by vramana** [comment]
@shivakrishna9 You are not supposed create PR from the master branch directly. You have to create a branch first and then PR from it.  See this https://guides.github.com/introduction/flow/

**Comment by shivakrishna9** [comment]
@vramana 
Do I have to delete commits and redo them or is there any workaround. I tried these
git reset 	6ea491c --hard ( to undo 3 commits )
git push origin +6ea491c:A5 ( to merge with branch A5)
 but failed.

**Comment by vramana** [comment]
First you have to update your local `master` branch (switch to master branch using `git checkout master`) using `git pull`. Then create a branch based of that branch. `git checkout -b my-branch-name` Then Add your commits here. Submit the PR. Once it's merged again update the master and start a new branch.

**Pull request closed without merging**
