### PR TITLE
happy for accomplishment

### PR DESCRIPTION
**Pull request by Agrawal-31**
I did't understood why activity 1 is going to pause state and resume again only on first run.

### CODE REVIEW

**Comment by mallelapavank** [comment]
Well done with HB and FB layouts. But looks like you just copy pasted my Button Click Counter app.

**Comment by Agrawal-31** [comment]
I didn't opened your counter app...I just did merger of both given links given in assignment 3

**Comment by Agrawal-31** [comment]
I watched many online videos...so that can be a reason

**Comment by shivakrishna9** [comment]
@aparichit007  When you feel like you are directly doing what is already in reference links or videos, try adding your own feature to it. This may be time consuming but we will learn a lot. Keep going!

**Comment by Agrawal-31** [comment]
Yeah!! Will update

**Comment by mallelapavank** [comment]
The assignment was to create your own app. That's how you learn, by doing it. Like @shivakrishna9 rightly mentioned try to think what you can add when you feel you already know something. That is a developer's mindset.

**Comment by M-ZubairAhmed** [comment]
could you separate PR based on assignments

**Comment by Agrawal-31** [comment]
how to send different PR for assignments

**Comment by mallelapavank** [comment]
Merging your PR, however you need to work on Button Click Counter app and send PR again.

**Pull request merged**
